blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.PostModelListView.as_view(), name="post_list"),
    path("post/create/", views.PostModelCreate.as_view(), name="post_create"),
    path("post/detail/<int:pk>/", views.PostModelDetailView.as_view(), name="post_detail"),
    path("post/<int:pk>/update/", views.PostModelUpdateView.as_view(), name="post_update"),
    path("post/<int:pk>/delete/", views.PostModelDeleteView.as_view(), name="post_delete"),
]

catalog/urls.py
from django.urls import path

from . import views

app_name = "catalog"

urlpatterns = [
    path("products/", views.ProductListView.as_view(), name="product_list"),
    path("contacts/", views.ContactsTemplateView.as_view(), name="contacts"),
    path("product/detail/<int:pk>/", views.ProductDetailView.as_view(), name="product_detail"),
    path("product/create/", views.ProductCreateView.as_view(), name="product_create"),
    path("product/update/<int:pk>/", views.ProductUpdateView.as_view(), name="product_update"),
    path("product/delete/<int:pk>/", views.ProductDeleteView.as_view(), name="product_delete"),
    path("category/", views.CategoryListView.as_view(), name="category_list"),
    path("category/create/", views.CategoryCreateView.as_view(), name="category_create"),
    path("product/<int:pk>/unpublish/", views.unpublish_product, name="unpublish_product"),
    path("product/<int:pk>/publish/", views.publish_product, name="publish_product"),
]

clients/urls.py
from django.urls import path

from . import views

app_name = "clients"

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.ClientLoginView.as_view(), name="login"),
    path("logout/", views.ClientLogoutView.as_view(), name="logout"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("clients/", include("clients.urls", namespace="clients")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse

from clients.models import Client


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Категория")
    description = models.TextField(verbose_name="Описание")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ["name"]


class Status(models.TextChoices):
    DRAFT = "DR", "Draft"
    PUBLISHED = "PB", "Published"


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name="Продукт")
    description = models.TextField(verbose_name="Описание")
    image = models.ImageField(upload_to="photos/", verbose_name="Фотография", blank=True)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="products", verbose_name="Категория продуктов"
    )
    price = models.PositiveIntegerField(verbose_name="Цена")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата добавление")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")
    status = models.CharField(
        max_length=2, choices=Status.choices, default=Status.DRAFT, verbose_name="Cтатус публикации"
    )
    owner = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name="Автор", blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"
        ordering = ["-created_at"]
        permissions = [
            ("can_unpublish_product", "Can unpublish product"),
            ("can_publish_product", "Can publish product"),
        ]

    def get_absolute_url(self):
        return reverse("catalog:product_detail", kwargs={"pk": self.pk})

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import Textarea

from .models import Category, Product

EXCLUDE_WORDS = ["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно", "обман", "полиция", "радар"]


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ["created_at", "updated_at", "owner"]

    def clean(self):
        cleaned_data = super().clean()
        name, description = cleaned_data.get("name"), cleaned_data.get("description")

        if any(word.lower() in name.lower() for word in EXCLUDE_WORDS):
            self.add_error("name", "В имени присутствует недопустимое слово")
        if any(word.lower() in description.lower() for word in EXCLUDE_WORDS):
            self.add_error("description", "В описании присутствует недопустимое слово")

    def clean_price(self):
        price = self.cleaned_data.get("price")
        if price < 0:
            raise ValidationError("Цена не может быть меньше нуля")
        return price

    def clean_image(self):
        image = self.cleaned_data.get("image")
        if image:
            if image.size > 5 * 1024 * 1024:  # 5 МБ
                raise forms.ValidationError("Файл не должен превышать 5 MB.")
            if not (image.name.endswith(".jpg") or image.name.endswith(".jpeg") or image.name.endswith(".png")):
                raise forms.ValidationError("Допустимые форматы: JPEG, PNG.")
        return image

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"
        self.fields["category"].widget.attrs.update({"class": "form-select"})


class ProductCreateForm(ProductForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        product = super().save(commit=False)
        if self.user and not product.pk:
            product.owner = self.user
        if commit:
            product.save()
        return product


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    phone = forms.IntegerField()
    message = forms.CharField(widget=Textarea)

    # def clean(self):
    #     cleaned_data = super().clean()
    #     name = cleaned_data.get("name")
    #     phone = cleaned_data.get("phone")
    #     message = cleaned_data.get("message")

catalog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, FormView, ListView, UpdateView

from catalog.models import Category, Product, Status

from .forms import CategoryForm, ContactForm, ProductCreateForm
from .mixins import OwnerOrModeratorMixins, OwnerRequiredMixin, ProductOwnerQuerysetMixin

from django.core.cache import cache
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator

from .service import ProductListService


class ContactsTemplateView(FormView):
    form_class = ContactForm
    template_name = "catalog/contacts.html"
    success_url = reverse_lazy("catalog:contacts")


class ProductListView(ProductOwnerQuerysetMixin, ListView):
    model = Product
    template_name = "catalog/product/product_list.html"
    context_object_name = "products"

    def get_queryset(self):
        queryset = cache.get("products_queryset")
        if not queryset:
            queryset = super().get_queryset()
            cache.set("products_queryset", queryset, 60 * 10)
        category_id = ProductListService.get_category_id(self.request)
        if category_id:
            queryset = queryset.filter(category_id=category_id)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = ProductListService.get_categories()
        context['selected_category'] = ProductListService.get_selected_categories(self.request)
        return context


@method_decorator(cache_page(60 * 10), name="dispatch")
class ProductDetailView(OwnerOrModeratorMixins, LoginRequiredMixin, DetailView):
    model = Product
    template_name = "catalog/product/product_detail.html"
    context_object_name = "product"
    login_url = reverse_lazy("clients:login")


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductCreateForm
    template_name = "catalog/product/product_form.html"
    success_url = reverse_lazy("catalog:product_list")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.owner = self.request.user
        messages.success(self.request, "Продукт успешно создан")
        return super().form_valid(form)


class ProductUpdateView(OwnerRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductCreateForm
    template_name = "catalog/product/product_form.html"

    def get_success_url(self):
        return reverse("catalog:product_detail", args=[self.kwargs.get("pk")])

    def form_valid(self, form):
        messages.success(self.request, "Продукт успешно обновлен")
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class ProductDeleteView(OwnerOrModeratorMixins, LoginRequiredMixin, DeleteView):
    model = Product
    template_name = "catalog/product/product_delete_confirm.html"
    success_url = reverse_lazy("catalog:product_list")


class CategoryListView(ListView):
    model = Category
    template_name = "catalog/category/category_list.html"
    context_object_name = "categories"


class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryForm
    template_name = "catalog/category/category_create.html"
    success_url = reverse_lazy("catalog:category_list")


@login_required
def unpublish_product(request, pk):
    product = get_object_or_404(Product, pk=pk)

    if product.owner != request.user and not request.user.has_perm("catalog.can_unpublish_product"):
        raise PermissionDenied("У вас нет прав для отмены публикации этого продукта")

    product.status = Status.DRAFT
    product.save()
    messages.success(request, "Публикация продукта отменена.")
    return redirect("catalog:product_detail", pk=product.pk)


@login_required
def publish_product(request, pk):
    product = get_object_or_404(Product, pk=pk)

    if product.owner != request.user and not request.user.has_perm("catalog.can_publish_product"):
        raise PermissionDenied("У вас нет прав для публикации этого продукта")

    if product.status == Status.DRAFT:
        product.status = Status.PUBLISHED
        product.save()
        messages.success(request, "Продукт успешно опубликован!")
    else:
        messages.warning(request, "Продукт уже опубликован.")

    return redirect("catalog:product_detail", pk=product.pk)

catalog/templates/catalog/includes/category_select.html
<div class="container mb-4">
    <form method="get" class="row g-3 align-items-center">
        <div class="col-auto">
            <label for="categorySelect" class="col-form-label">Выбрать категорию:</label>
        </div>
        <div class="col-auto">
            <select name="category" id="categorySelect" class="form-select" onchange="this.form.submit()">
                <option value="">Все категории</option>
                {% for category in categories %}
                <option value="{{ category.id }}"
                    {% if selected_category == category.id|stringformat:"i" %}selected{% endif %}>
                    {{ category.name }}
                </option>
                {% endfor %}
            </select>
        </div>
        <div class="col-auto">
      <!--     <button type="submit" class="btn btn-outline-primary">Применить</button> -->
            {% if selected_category %}
            <a href="{% url 'catalog:product_list' %}" class="btn btn-outline-secondary">Сбросить</a>
            {% endif %}
        </div>
    </form>
</div>

catalog/templates/catalog/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

catalog/templates/catalog/includes/header.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_list'%}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/catalog/contacts/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:post_list' %}">Блог</a>
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <form method="post" action="{% url 'clients:logout' %}" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="p-2 btn btn-outline-primary">
                        Выход
                    </button>
                </form>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="p-2 btn btn-outline-primary" href="{% url 'clients:login' %}">Войти</a>
            </li>
            <li class="nav-item">
                <a class="p-2 btn btn-outline-primary" href="{% url 'clients:register' %}">Регистрация</a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>