blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.PostModelListView.as_view(), name="post_list"),
    path("post/create/", views.PostModelCreate.as_view(), name="post_create"),
    path("post/detail/<int:pk>/", views.PostModelDetailView.as_view(), name="post_detail"),
    path("post/<int:pk>/update/", views.PostModelUpdateView.as_view(), name="post_update"),
    path("post/<int:pk>/delete/", views.PostModelDeleteView.as_view(), name="post_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("clients/", include("clients.urls", namespace="clients")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DR", "Draft"
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=150, verbose_name="Заголовок")
    body = models.TextField(verbose_name="Содержание")
    image = models.ImageField(upload_to="photos/blog/", verbose_name="Фотография", blank=True)
    publish_at = models.DateTimeField(default=timezone.now, verbose_name="Дата публикации")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Последнее обновление")
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT, verbose_name="Статус")
    views_count = models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")
    is_active = models.BooleanField(default=True, verbose_name="Статус публикации")
    objects = models.Manager()
    published = PublishedManager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "пост"
        verbose_name_plural = "посты"
        ordering = ["-publish_at"]
        indexes = [models.Index(fields=["-publish_at"])]

blog/views.py
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from .models import Post


class PostModelCreate(CreateView):
    model = Post
    fields = ["title", "body", "image", "status", "is_active"]
    template_name = "blog/post/post_form.html"
    success_url = reverse_lazy("blog:post_list")


class PostModelUpdateView(UpdateView):
    model = Post
    fields = ["title", "body", "image", "status"]
    template_name = "blog/post/post_form.html"

    def get_success_url(self):
        return reverse("blog:post_detail", args=[self.kwargs.get("pk")])


class PostModelListView(ListView):
    model = Post
    template_name = "blog/post/post_list.html"
    context_object_name = "posts"

    def get_queryset(self):
        return Post.objects.filter(is_active=True)


class PostModelDetailView(DetailView):
    model = Post
    template_name = "blog/post/post_detail.html"
    context_object_name = "post"

    def get_object(self, queryset=None):
        post = super().get_object()
        post.views_count += 1
        post.save()
        return post


class PostModelDeleteView(DeleteView):
    model = Post
    template_name = "blog/post/post_delete_confirm.html"
    success_url = reverse_lazy("blog:post_list")

blog/templates/blog/post/post_delete_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Удалить объект Post</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
<div class="container mt-5">
    <h1 class="mb-4">Удалить объект {{ post.title }}</h1>
    <p>Вы уверены, что хотите удалить {{ post.name }}?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'blog:post_list' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
<script src="/static/js/bootstrap.min.js"></script>
</body>
</html>

blog/templates/blog/post/post_detail.html
{% extends "catalog/base.html" %}
{% block content %}
<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Создан: {{ post.created_at|date:'d.m.Y' }} | Просмотров:
                {{ post.views_count }}</h6>
            {% if post.image %}
            <img src="{{ post.image.url }}" class="card-img-top" alt="Превью"
                 style="max-width: 100%; height: auto; width: auto; max-height: 200px;">
            {% endif %}
            <p class="card-text">{{ post.body }}</p>
        </div>
    </div>
    <div class="mt-3">
        <a href="{% url 'blog:post_update' post.pk %}" class="btn btn-warning btn-lg">Редактировать</a>
        <a href="{% url 'blog:post_delete' post.pk %}" class="btn btn-danger btn-lg">Удалить</a>
        <a href="{% url 'blog:post_list' %}" class="btn btn-secondary btn-lg">Назад к списку</a>
    </div>
</div>
{% endblock %}

blog/templates/blog/post/post_form.html
{% extends "catalog/base.html" %}
{% block content %}
<div class="container mt-4">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{% if form.instance.pk %}Редактировать пост{% else %}Создать пост{% endif %}</h1>
    </div>
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="card-8">
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary btn-lg mt-3">Сохранить</button>
            <a href="{% url 'blog:post_list' %}" class="btn btn-secondary btn-lg mt-3">Отменить</a>
        </div>


    </form>
</div>
{% endblock %}

blog/templates/blog/post/post_list.html
{% extends "catalog/base.html" %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Список постов</h1>
</div>

<div class="container mt-4">
    <a href="{% url 'blog:post_create' %}" class="btn btn-primary mb-3 btn-lg">Создать новый пост</a>
    <div class="list-group">
        {% for post in posts %}
        <a href="{% url 'blog:post_detail' post.pk%}" class="list-group-item list-group-item-action">
            <h5 class="mb-1">{{ post.title }}</h5>
            <small>Создан: {{ post.created_at|date:'d.m.Y' }} | Последнее обновление {{ post.updated_at|date:'d.m.Y' }}</small><br>
            <small>Содержимое: {{ post.body|truncatewords:20|linebreaks }}</small><br>
            <small><u>Просмотров:</u> {{ post.views_count }}</small>
        </a>
        {% empty %}
        <div class="alert alert-warning b">Посты отсутствуют.</div>
        {% endfor %}
    </div>
</div>
{% endblock %}